разметка главной страницы
htmlacademy-adaptive/1486905-cat-energy-23 pull request #2
Opened 2021-07-24 18:17 UTC by KoshkinaECat

2021-07-24 23:27 UTC, Zakamsky requested changes
Небольшая путаница, но в целом все хорошо. Просто тема большая и сложная.
Давай все же все поправим, что бы на внутренних страницах уже не делать таких ошибок.
з.ю. станет понятнее когда начнем писать стили.

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +<!DOCTYPE html>
`source/html/index.html` весь штмл должен лежать непосредственно в папке `source` он оттуда публикуется.
пока ничего страшного, но надо будет переложить.

2021-07-24 23:27 UTC, Zakamsky commented on Readme.md
:) сравни синтаксис  в этих строках, и посмотри на опубликованный ридми
![image](https://user-images.githubusercontent.com/35491086/126882973-59c5c8b2-11a3-4a07-a6e1-7a2efd87dd4a.png)

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +    </a>
Это в принципе не ошибка, но лучше в таком случае было бы переименовать файл. представь что завтра наймут фрилансера на сайте лого убрать из подвала, или поменять на другую картинку.
и... удалит из папки со спокойной совестью...
Или ты сама через полгода в подвале ее поменяешь, и не вспомнишь что она еще где то используется кроме футера.
И пару слов о консистентности... почему `logo-mobile` но `footer-logo` ?
з.ы. первый вариант лучше, т.к. все варианты лого будут лежать рядом.

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +          <li class="main-nav__item--active">
базовая идея модификатора такая:
мы пишем одинаковые стили, например размер текста, отступы, цвет, на сам класс, например `.block__element` а потом для `.block__element--modifier` указываем только то что отличается, например жирность или подчеркивание.
Как ты думаешь если мы не укажем одновременно `.block__element.block__element--modifier` а напишем только `.block__element--modifier` что будет?

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +          <a class="promo_button" href="form.html">Подобрать программу</a>
тут наверное опечатка, двойное подчеркивание разделяется блок и элемент, по методологии.

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +     </li>
опять потеряли сами элементы, указали только классы модификаторов.

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +<p class="example__result">Стало</p>
Опечатка в классах картинок, надо бы двойной подчеркивание.
А еще тут можно добавить какую то оберточку для картинок, и рэйндж слайдер для бегунка, но это так, совет...

2021-07-24 23:27 UTC, Zakamsky commented on source/html/index.html
> +            </ul>
А вот тут модификаторы написаны прямо показательно, но потерялся сам блок  `social` есть только его элементы.

2021-07-25 05:44 UTC, KoshkinaECat commented on Readme.md
кажется получилось...)

2021-07-27 11:40 UTC, Zakamsky approved these changes
Отличая работа над ошибками ( мелкую опечатка отправил в личку).
Принято.

2021-07-27 13:36 UTC, merged